FROM nginx:1.23.3

RUN groupadd -r --gid 1001 ops && \
    useradd -r --uid 1001 -g ops ops && \
    chmod -R 777 /var/cache/nginx && \
    chmod -R 777 /var/run

USER ops
EXPOSE 80 8080 443
CMD ["nginx", "-g", "daemon off;"];
